### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by LightSun** [M4GNV5/PointerScript#6]
```
./bin/ptrs examples/struct.ptrs 
*** invalid %N$ use detected ***
Received signal: Aborted
```
system info
```
ubuntu 18.04
```

**Comment by M4GNV5** [comment]
Hey,

when i run the struct example everything looks fine:

```bash
$ bin/ptrs examples/struct.ptrs 
Foo:0x56375bb33e50 - 42
getting property fooval.foo = foo
Foo:0x56375bb33e50 - 42
milliseconds since epoch: 1661168257372
```

Did you compile ptrs with special parameters? What libc(-version) do you use? Can you run `./runTests` this runs a set of test cases. Just to see if some of them fail, all of them or none.

**Comment by LightSun** [comment]
@M4GNV5 
glibc version
```
ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1.5) 2.27
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```
the result of ./runTests
```
./runTests.sh 
SUCCESS running test runtime/interop
SUCCESS running test runtime/interop with arguments -O0
SUCCESS running test runtime/interop with arguments -O1
SUCCESS running test runtime/interop with arguments -O2
SUCCESS running test runtime/interop with arguments --no-predictions
SUCCESS running test runtime/interop with arguments --no-predictions -O0
SUCCESS running test runtime/interop with arguments --no-predictions -O1
SUCCESS running test runtime/interop with arguments --no-predictions -O2
SUCCESS running test runtime/pointer
SUCCESS running test runtime/pointer with arguments -O0
SUCCESS running test runtime/pointer with arguments -O1
SUCCESS running test runtime/pointer with arguments -O2
SUCCESS running test runtime/pointer with arguments --no-predictions
SUCCESS running test runtime/pointer with arguments --no-predictions -O0
SUCCESS running test runtime/pointer with arguments --no-predictions -O1
SUCCESS running test runtime/pointer with arguments --no-predictions -O2
SUCCESS running test runtime/types
SUCCESS running test runtime/types with arguments -O0
SUCCESS running test runtime/types with arguments -O1
SUCCESS running test runtime/types with arguments -O2
SUCCESS running test runtime/types with arguments --no-predictions
SUCCESS running test runtime/types with arguments --no-predictions -O0
SUCCESS running test runtime/types with arguments --no-predictions -O1
SUCCESS running test runtime/types with arguments --no-predictions -O2
SUCCESS running test runtime/conversion
SUCCESS running test runtime/conversion with arguments -O0
SUCCESS running test runtime/conversion with arguments -O1
SUCCESS running test runtime/conversion with arguments -O2
SUCCESS running test runtime/conversion with arguments --no-predictions
SUCCESS running test runtime/conversion with arguments --no-predictions -O0
SUCCESS running test runtime/conversion with arguments --no-predictions -O1
SUCCESS running test runtime/conversion with arguments --no-predictions -O2
SUCCESS running test runtime/loops
SUCCESS running test runtime/loops with arguments -O0
SUCCESS running test runtime/loops with arguments -O1
SUCCESS running test runtime/loops with arguments -O2
SUCCESS running test runtime/loops with arguments --no-predictions
SUCCESS running test runtime/loops with arguments --no-predictions -O0
SUCCESS running test runtime/loops with arguments --no-predictions -O1
SUCCESS running test runtime/loops with arguments --no-predictions -O2
SUCCESS running test runtime/switch
SUCCESS running test runtime/switch with arguments -O0
SUCCESS running test runtime/switch with arguments -O1
SUCCESS running test runtime/switch with arguments -O2
SUCCESS running test runtime/switch with arguments --no-predictions
SUCCESS running test runtime/switch with arguments --no-predictions -O0
SUCCESS running test runtime/switch with arguments --no-predictions -O1
SUCCESS running test runtime/switch with arguments --no-predictions -O2
SUCCESS running test runtime/strformat
SUCCESS running test runtime/strformat with arguments -O0
SUCCESS running test runtime/strformat with arguments -O1
SUCCESS running test runtime/strformat with arguments -O2
SUCCESS running test runtime/strformat with arguments --no-predictions
SUCCESS running test runtime/strformat with arguments --no-predictions -O0
SUCCESS running test runtime/strformat with arguments --no-predictions -O1
SUCCESS running test runtime/strformat with arguments --no-predictions -O2
SUCCESS running test runtime/struct
SUCCESS running test runtime/struct with arguments -O0
SUCCESS running test runtime/struct with arguments -O1
SUCCESS running test runtime/struct with arguments -O2
SUCCESS running test runtime/struct with arguments --no-predictions
SUCCESS running test runtime/struct with arguments --no-predictions -O0
SUCCESS running test runtime/struct with arguments --no-predictions -O1
SUCCESS running test runtime/struct with arguments --no-predictions -O2
TRYING test runtime/overload
*** invalid %N$ use detected ***
Received signal: Aborted

ERROR running test runtime/overload
TRYING test runtime/overload with arguments -O0
*** invalid %N$ use detected ***
Received signal: Aborted

ERROR running test runtime/overload with arguments -O0
TRYING test runtime/overload with arguments -O1
*** invalid %N$ use detected ***
Received signal: Aborted

ERROR running test runtime/overload with arguments -O1
TRYING test runtime/overload with arguments -O2
*** invalid %N$ use detected ***
Received signal: Aborted

ERROR running test runtime/overload with arguments -O2
TRYING test runtime/overload with arguments --no-predictions
*** invalid %N$ use detected ***
Received signal: Aborted

ERROR running test runtime/overload with arguments --no-predictions
TRYING test runtime/overload with arguments --no-predictions -O0
*** invalid %N$ use detected ***
Received signal: Aborted

ERROR running test runtime/overload with arguments --no-predictions -O0
TRYING test runtime/overload with arguments --no-predictions -O1
*** invalid %N$ use detected ***
Received signal: Aborted

ERROR running test runtime/overload with arguments --no-predictions -O1
TRYING test runtime/overload with arguments --no-predictions -O2
*** invalid %N$ use detected ***
Received signal: Aborted

ERROR running test runtime/overload with arguments --no-predictions -O2
SUCCESS running test runtime/functions
SUCCESS running test runtime/functions with arguments -O0
SUCCESS running test runtime/functions with arguments -O1
SUCCESS running test runtime/functions with arguments -O2
SUCCESS running test runtime/functions with arguments --no-predictions
SUCCESS running test runtime/functions with arguments --no-predictions -O0
SUCCESS running test runtime/functions with arguments --no-predictions -O1
SUCCESS running test runtime/functions with arguments --no-predictions -O2
SUCCESS running test runtime/alignment
SUCCESS running test runtime/alignment with arguments -O0
SUCCESS running test runtime/alignment with arguments -O1
SUCCESS running test runtime/alignment with arguments -O2
SUCCESS running test runtime/alignment with arguments --no-predictions
SUCCESS running test runtime/alignment with arguments --no-predictions -O0
SUCCESS running test runtime/alignment with arguments --no-predictions -O1
SUCCESS running test runtime/alignment with arguments --no-predictions -O2
SUCCESS running test runtime/operators
SUCCESS running test runtime/operators with arguments -O0
SUCCESS running test runtime/operators with arguments -O1
SUCCESS running test runtime/operators with arguments -O2
SUCCESS running test runtime/operators with arguments --no-predictions
SUCCESS running test runtime/operators with arguments --no-predictions -O0
SUCCESS running test runtime/operators with arguments --no-predictions -O1
SUCCESS running test runtime/operators with arguments --no-predictions -O2

```

**Comment by M4GNV5** [comment]
I've managed to reproduce the error via an Ubuntu 18.04 docker container:

```Dockerfile
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y build-essential bison flex autoconf automake libtool texinfo gdb valgrind

WORKDIR /opt
COPY . .
RUN cd /opt && ls -lah && make -j4

CMD bin/ptrs examples/struct.ptrs
```

running gdb inside docker gives us a stacktrace:
```bash
# docker build . -t ptrs-test
[...]
# docker run -it ptrs-test bash
root@bb6c253a51af:/opt# gdb -q bin/ptrs 
Reading symbols from bin/ptrs...done.
(gdb) r examples/struct.ptrs
Starting program: /opt/bin/ptrs examples/struct.ptrs
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
*** invalid %N$ use detected ***

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) back
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fa85eef27f1 in __GI_abort () at abort.c:79
#2  0x00007fa85ef3b585 in __libc_message (action=(do_abort | do_backtrace), fmt=0x7fa85f068677 "%s", fmt=0x7fa85f068677 "%s", 
    action=(do_abort | do_backtrace)) at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007fa85ef3b8ca in __GI___libc_fatal (message=message@entry=0x7fa85f069b60 "*** invalid %N$ use detected ***\n")
    at ../sysdeps/posix/libc_fatal.c:191
#4  0x00007fa85ef0b159 in printf_positional (s=s@entry=0x7ffdfc820b50, format=format@entry=0x5575dd09493d "%1$s.op this[%3$s]", 
    readonly_format=readonly_format@entry=0, ap=ap@entry=0x7ffdfc820cd0, ap_savep=ap_savep@entry=0x7ffdfc8206f8, done=done@entry=0, 
    nspecs_done=<optimized out>, lead_str_end=<optimized out>, work_buffer=<optimized out>, save_errno=<optimized out>, grouping=0x0, 
    thousands_sep=0x7fa85f065b67 "") at vfprintf.c:1893
#5  0x00007fa85ef0ec8a in _IO_vfprintf_internal (s=s@entry=0x7ffdfc820b50, format=format@entry=0x5575dd09493d "%1$s.op this[%3$s]", 
    ap=ap@entry=0x7ffdfc820cd0) at vfprintf.c:1688
#6  0x00007fa85efe3fc9 in ___vsnprintf_chk (s=0x7ffdfc820c40 "", maxlen=<optimized out>, flags=1, slen=<optimized out>, 
    format=0x5575dd09493d "%1$s.op this[%3$s]", args=args@entry=0x7ffdfc820cd0) at vsnprintf_chk.c:63
#7  0x00007fa85efe3ef5 in ___snprintf_chk (s=s@entry=0x0, maxlen=maxlen@entry=0, flags=flags@entry=1, 
    slen=slen@entry=18446744073709551615, format=format@entry=0x5575dd09493d "%1$s.op this[%3$s]") at snprintf_chk.c:34
#8  0x00005575dd0230c1 in snprintf (__fmt=0x5575dd09493d "%1$s.op this[%3$s]", __n=0, __s=0x0)
    at /usr/include/x86_64-linux-gnu/bits/stdio2.h:64
#9  parseStruct (code=code@entry=0x7ffdfc821070, struc=struc@entry=0x5575de067d60) at parser/ast.c:2300
#10 0x00005575dd02573e in parseStatement (code=0x7ffdfc821070) at parser/ast.c:713
#11 0x00005575dd0260a8 in parseStmtList (code=code@entry=0x7ffdfc821070, end=end@entry=0 '\000') at parser/ast.c:285
#12 0x00005575dd02631d in ptrs_parse (
    src=src@entry=0x5575de068760 "import puts, printf, gettimeofday;\n\nstruct Foo\n{\n\t//struct can have field-,\n\tvalue = 42;\n\t//array-\n\tmyByteArray: u8[128];\n\t//var-array-\n\tmyValues: var[42];\n\t//and function-members\n\tdump()\n\t{\n\t\tputs(\"$"..., 
    filename=filename@entry=0x5575de067750 "examples/struct.ptrs", symbols=symbols@entry=0x7ffdfc821628, 
    addInitRoot=addInitRoot@entry=true) at parser/ast.c:174
#13 0x00005575dd036157 in ptrs_compile (result=result@entry=0x7ffdfc821620, 
    src=src@entry=0x5575de068760 "import puts, printf, gettimeofday;\n\nstruct Foo\n{\n\t//struct can have field-,\n\tvalue = 42;\n\t//array-\n\tmyByteArray: u8[128];\n\t//var-array-\n\tmyValues: var[42];\n\t//and function-members\n\tdump()\n\t{\n\t\tputs(\"$"..., 
    filename=0x5575de067750 "examples/struct.ptrs") at jit/lib/run.c:29
#14 0x00005575dd036378 in ptrs_compilefile (result=0x7ffdfc821620, file=0x7ffdfc823946 "examples/struct.ptrs") at jit/lib/run.c:78
#15 0x00005575dd023b10 in main (argc=<optimized out>, argv=<optimized out>) at jit/main.c:164
```

[The snprintf here used for generating struct function names](https://github.com/M4GNV5/PointerScript/blob/master/parser/ast.c#L2300) causes the error.
Its not quite clear to me why the use would be invalid. I found [this issue with the same problem](https://github.com/radareorg/radare2/issues/3944#issuecomment-207874378). Adding the `-U_FORTIFY_SOURCE` to the `CFLAGS` does indeed solve the problem, but disabling security features does not sound like a good idea.

For now you can use the fix, but in the long run the `parseStruct` function should be refactored to not use `%N$` formatting which is a non-C-standard functionality anyways.

**Comment by LightSun** [comment]
@M4GNV5 after I add  -U_FORTIFY_SOURCE.  Cause another problem.
```
./runTests.sh 
SUCCESS running test runtime/interop
SUCCESS running test runtime/interop with arguments -O0
SUCCESS running test runtime/interop with arguments -O1
SUCCESS running test runtime/interop with arguments -O2
SUCCESS running test runtime/interop with arguments --no-predictions
SUCCESS running test runtime/interop with arguments --no-predictions -O0
SUCCESS running test runtime/interop with arguments --no-predictions -O1
SUCCESS running test runtime/interop with arguments --no-predictions -O2
SUCCESS running test runtime/pointer
SUCCESS running test runtime/pointer with arguments -O0
SUCCESS running test runtime/pointer with arguments -O1
SUCCESS running test runtime/pointer with arguments -O2
SUCCESS running test runtime/pointer with arguments --no-predictions
SUCCESS running test runtime/pointer with arguments --no-predictions -O0
SUCCESS running test runtime/pointer with arguments --no-predictions -O1
SUCCESS running test runtime/pointer with arguments --no-predictions -O2
SUCCESS running test runtime/types
SUCCESS running test runtime/types with arguments -O0
SUCCESS running test runtime/types with arguments -O1
SUCCESS running test runtime/types with arguments -O2
SUCCESS running test runtime/types with arguments --no-predictions
SUCCESS running test runtime/types with arguments --no-predictions -O0
SUCCESS running test runtime/types with arguments --no-predictions -O1
SUCCESS running test runtime/types with arguments --no-predictions -O2
SUCCESS running test runtime/conversion
SUCCESS running test runtime/conversion with arguments -O0
SUCCESS running test runtime/conversion with arguments -O1
SUCCESS running test runtime/conversion with arguments -O2
SUCCESS running test runtime/conversion with arguments --no-predictions
SUCCESS running test runtime/conversion with arguments --no-predictions -O0
SUCCESS running test runtime/conversion with arguments --no-predictions -O1
SUCCESS running test runtime/conversion with arguments --no-predictions -O2
SUCCESS running test runtime/loops
SUCCESS running test runtime/loops with arguments -O0
SUCCESS running test runtime/loops with arguments -O1
SUCCESS running test runtime/loops with arguments -O2
SUCCESS running test runtime/loops with arguments --no-predictions
SUCCESS running test runtime/loops with arguments --no-predictions -O0
SUCCESS running test runtime/loops with arguments --no-predictions -O1
SUCCESS running test runtime/loops with arguments --no-predictions -O2
SUCCESS running test runtime/switch
SUCCESS running test runtime/switch with arguments -O0
SUCCESS running test runtime/switch with arguments -O1
SUCCESS running test runtime/switch with arguments -O2
SUCCESS running test runtime/switch with arguments --no-predictions
SUCCESS running test runtime/switch with arguments --no-predictions -O0
SUCCESS running test runtime/switch with arguments --no-predictions -O1
SUCCESS running test runtime/switch with arguments --no-predictions -O2
SUCCESS running test runtime/strformat
SUCCESS running test runtime/strformat with arguments -O0
SUCCESS running test runtime/strformat with arguments -O1
SUCCESS running test runtime/strformat with arguments -O2
SUCCESS running test runtime/strformat with arguments --no-predictions
SUCCESS running test runtime/strformat with arguments --no-predictions -O0
SUCCESS running test runtime/strformat with arguments --no-predictions -O1
SUCCESS running test runtime/strformat with arguments --no-predictions -O2
SUCCESS running test runtime/struct
SUCCESS running test runtime/struct with arguments -O0
SUCCESS running test runtime/struct with arguments -O1
SUCCESS running test runtime/struct with arguments -O2
SUCCESS running test runtime/struct with arguments --no-predictions
SUCCESS running test runtime/struct with arguments --no-predictions -O0
SUCCESS running test runtime/struct with arguments --no-predictions -O1
SUCCESS running test runtime/struct with arguments --no-predictions -O2
TRYING test runtime/overload
Expected [undefined] got [1] at /home/heaven7/heaven7/temp/PointerScript/tests/common.ptrs:25:3

		throw msg;
		^


ERROR running test runtime/overload
TRYING test runtime/overload with arguments -O0
Expected [undefined] got [1] at /home/heaven7/heaven7/temp/PointerScript/tests/common.ptrs:25:3

		throw msg;
		^


ERROR running test runtime/overload with arguments -O0
TRYING test runtime/overload with arguments -O1
Expected [undefined] got [1] at /home/heaven7/heaven7/temp/PointerScript/tests/common.ptrs:25:3

		throw msg;
		^


ERROR running test runtime/overload with arguments -O1
TRYING test runtime/overload with arguments -O2
Expected [undefined] got [1] at /home/heaven7/heaven7/temp/PointerScript/tests/common.ptrs:25:3

		throw msg;
		^


ERROR running test runtime/overload with arguments -O2
SUCCESS running test runtime/overload with arguments --no-predictions
SUCCESS running test runtime/overload with arguments --no-predictions -O0
SUCCESS running test runtime/overload with arguments --no-predictions -O1
SUCCESS running test runtime/overload with arguments --no-predictions -O2
SUCCESS running test runtime/functions
SUCCESS running test runtime/functions with arguments -O0
SUCCESS running test runtime/functions with arguments -O1
SUCCESS running test runtime/functions with arguments -O2
SUCCESS running test runtime/functions with arguments --no-predictions
SUCCESS running test runtime/functions with arguments --no-predictions -O0
SUCCESS running test runtime/functions with arguments --no-predictions -O1
SUCCESS running test runtime/functions with arguments --no-predictions -O2
SUCCESS running test runtime/alignment
SUCCESS running test runtime/alignment with arguments -O0
SUCCESS running test runtime/alignment with arguments -O1
SUCCESS running test runtime/alignment with arguments -O2
SUCCESS running test runtime/alignment with arguments --no-predictions
SUCCESS running test runtime/alignment with arguments --no-predictions -O0
SUCCESS running test runtime/alignment with arguments --no-predictions -O1
SUCCESS running test runtime/alignment with arguments --no-predictions -O2
SUCCESS running test runtime/operators
SUCCESS running test runtime/operators with arguments -O0
SUCCESS running test runtime/operators with arguments -O1
SUCCESS running test runtime/operators with arguments -O2
SUCCESS running test runtime/operators with arguments --no-predictions
SUCCESS running test runtime/operators with arguments --no-predictions -O0
SUCCESS running test runtime/operators with arguments --no-predictions -O1
SUCCESS running test runtime/operators with arguments --no-predictions -O2

```
